"""Streaming H.264 Annex-B helpers.

The DrongScreen APK forwards MediaCodec output buffers directly.  Those buffers
retain Annex-B start codes, and the APK explicitly inspects byte 4 for ``0x65`` to
identify an IDR NAL.  This module therefore *preserves* every 3- or 4-byte start
code instead of stripping it.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import BinaryIO
from pathlib import Path


class AnnexBError(ValueError):
    pass


def _find_start_code(data: bytes | bytearray, start: int = 0) -> tuple[int, int] | None:
    limit = len(data) - 2
    i = max(0, start)
    while i < limit:
        if data[i] == 0 and data[i + 1] == 0:
            if i + 3 < len(data) and data[i + 2] == 0 and data[i + 3] == 1:
                return i, 4
            if data[i + 2] == 1:
                return i, 3
        i += 1
    return None


def start_code_length(nal: bytes) -> int:
    if nal.startswith(b"\x00\x00\x00\x01"):
        return 4
    if nal.startswith(b"\x00\x00\x01"):
        return 3
    raise AnnexBError("NAL unit does not begin with an Annex-B start code")


def nal_unit_type(nal: bytes) -> int:
    offset = start_code_length(nal)
    if len(nal) <= offset:
        raise AnnexBError("empty NAL unit")
    return nal[offset] & 0x1F


def iter_nals(stream: BinaryIO, *, chunk_size: int = 256 * 1024) -> Iterator[bytes]:
    """Yield complete Annex-B NAL units, including their original start codes."""

    if chunk_size < 8:
        raise ValueError("chunk_size must be at least 8")

    buffer = bytearray()
    first_found = False

    while True:
        chunk = stream.read(chunk_size)
        eof = not chunk
        if chunk:
            buffer.extend(chunk)

        if not first_found:
            first = _find_start_code(buffer)
            if first is None:
                if eof:
                    if buffer:
                        raise AnnexBError("no Annex-B start code found")
                    return
                # Keep a tiny suffix in case the start code straddles reads.
                if len(buffer) > 4:
                    del buffer[:-4]
                continue
            if first[0] > 0:
                del buffer[: first[0]]
            first_found = True

        while True:
            current = _find_start_code(buffer, 0)
            if current is None or current[0] != 0:
                raise AnnexBError("internal parser lost NAL synchronization")
            following = _find_start_code(buffer, current[1])
            if following is None:
                break
            nal = bytes(buffer[: following[0]])
            del buffer[: following[0]]
            if len(nal) > current[1]:
                yield nal

        if eof:
            if buffer:
                current = _find_start_code(buffer, 0)
                if current is not None and current[0] == 0 and len(buffer) > current[1]:
                    yield bytes(buffer)
            return


def iter_access_units(nals: Iterator[bytes]) -> Iterator[bytes]:
    """Group NALs at AUD (type 9) boundaries.

    Test streams generated by this project insert AUD NALs.  If a stream contains
    no AUDs, each NAL is yielded independently rather than trying to implement a
    full H.264 slice-header parser.
    """

    pending: list[bytes] = []
    saw_aud = False

    for nal in nals:
        nal_type = nal_unit_type(nal)
        if nal_type == 9:
            if pending:
                yield b"".join(pending)
                pending = []
            saw_aud = True
            pending.append(nal)
        elif saw_aud:
            pending.append(nal)
        else:
            yield nal

    if pending:
        yield b"".join(pending)


def iter_h264_packets_from_stream(
    stream: BinaryIO,
    *,
    packetization: str = "access-unit",
    chunk_size: int = 256 * 1024,
) -> Iterator[bytes]:
    nals = iter_nals(stream, chunk_size=chunk_size)
    if packetization == "nal":
        yield from nals
    elif packetization == "access-unit":
        yield from iter_access_units(nals)
    else:
        raise ValueError("packetization must be 'nal' or 'access-unit'")


def iter_h264_packets(
    path: str | Path,
    *,
    packetization: str = "access-unit",
    chunk_size: int = 256 * 1024,
) -> Iterator[bytes]:
    path = Path(path)
    with path.open("rb") as stream:
        yield from iter_h264_packets_from_stream(
            stream, packetization=packetization, chunk_size=chunk_size
        )
